# Setup:

In [111]:
import torch
from transformers import AdamW, AutoTokenizer, AutoModelForSequenceClassification, Trainer, TrainingArguments, get_cosine_schedule_with_warmup
from tqdm import tqdm
import os
from datasets import Dataset
import random
from sklearn.metrics import precision_recall_fscore_support, accuracy_score, confusion_matrix
import numpy as np
from collections import defaultdict
from tqdm import tqdm
import concurrent.futures
from functools import partial
from itertools import product

os.environ["CUDA_LAUNCH_BLOCKING"] = "1"
DATASET_ROOT = "../../CrossVul"
#DATASET_ROOT = "../../Preprocessed/Rename"
#DATASET_ROOT = "../../Preprocessed/NoRename"
DATASET_ROOTS = ["../../CrossVul", "../../Preprocessed/Rename", "../../Preprocessed/NoRename"]
ALLOWED_CWE_IDS = {"CWE-79", "CWE-787", "CWE-89"} # "CWE-79", "CWE-787", "CWE-89"
LANGUAGES = ['c', 'cpp', 'cs', 'java', 'py', 'php']
SEED = 42
EPOCHS = 3

In [112]:
vulBERTa = "claudios/VulBERTa-MLP-ReVeal"
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer = AutoTokenizer.from_pretrained(vulBERTa, trust_remote_code=True)
print(device)

cuda

In [113]:
class FileAwareTrainer(Trainer):
    def __init__(self, *args, eval_dataset_filenames=None, **kwargs):
        super().__init__(*args, **kwargs)
        self.eval_dataset_filenames = eval_dataset_filenames

    def evaluate(self, eval_dataset=None, **kwargs):
        output = super().evaluate(eval_dataset=eval_dataset, **kwargs)
        self._last_eval_preds = kwargs.get('preds', None)
        return output

    def predict(self, test_dataset, **kwargs):
        self.eval_dataset_filenames = test_dataset['filename']
        return super().predict(test_dataset, **kwargs)

# Data Preprocessing

In [114]:
def collect_files_for_cwe(cwe_id, dataset):
    samples = []
    for lang in LANGUAGES:
        lang_dir = os.path.join(dataset, cwe_id, lang)
        if not os.path.isdir(lang_dir):
            continue
        for filename in os.listdir(lang_dir):
            filepath = os.path.join(lang_dir, filename)
            if filename.endswith('.DS_Store'):
                continue
            label = 1 if "bad" in filename.lower() else 0
            with open(filepath, 'r', encoding='utf-8', errors='ignore') as f:
                code = f.read()
            samples.append({
                "filename": filename,
                "code": code,
                "label": label
            })
    print(len(samples))
    return samples

def compute_file_metrics_builder(filenames, thresh):
    def compute_file_metrics(eval_pred):
        logits, labels = eval_pred
        preds = np.argmax(logits, axis=-1)

        file_pred_chunks = defaultdict(list)
        file_label = {}

        for pred, label, fname in zip(preds, labels, filenames):
            file_pred_chunks[fname].append(pred)
            file_label[fname] = label

        final_preds, final_labels = [], []
        for fname in file_pred_chunks:
            final_labels.append(file_label[fname])
            vulnerable_chunks = sum(1 for pred in file_pred_chunks[fname] if pred == 1)
            if vulnerable_chunks / len(file_pred_chunks[fname]) >= thresh:
                final_preds.append(1)
            else:
                final_preds.append(0)

        precision, recall, f1, _ = precision_recall_fscore_support(final_labels, final_preds, average='binary')
        acc = accuracy_score(final_labels, final_preds)
        confusion = confusion_matrix(final_labels, final_preds).tolist()
        ch_confusion = confusion_matrix(labels, preds).tolist()
        print(f"file level: {confusion}")
        print(f"chunk level: {ch_confusion}")
        return {
            'accuracy': acc,
            'precision': precision,
            'recall': recall,
            'f1': f1,
            "confusion_matrix": confusion
        }

    return compute_file_metrics

def tokenize_example(batch, max_length=512):
    input_ids_list = []
    attention_mask_list = []
    labels_list = []
    filenames_list = []

    for code, label, filename in zip(batch["code"], batch["label"], batch["filename"]):
        tokens = tokenizer(code, return_attention_mask=True, truncation=False)
        input_ids = tokens["input_ids"]
        attention_mask = tokens["attention_mask"]

        for i in range(0, len(input_ids), max_length):
            chunk_ids = input_ids[i:i + max_length]
            chunk_mask = attention_mask[i:i + max_length]

            pad_len = max_length - len(chunk_ids)
            if pad_len > 0:
                chunk_ids += [tokenizer.pad_token_id] * pad_len
                chunk_mask += [0] * pad_len

            input_ids_list.append(chunk_ids)
            attention_mask_list.append(chunk_mask)
            labels_list.append(label)
            filenames_list.append(filename)

    return {
        "input_ids": input_ids_list,
        "attention_mask": attention_mask_list,
        "label": labels_list,
        "filename": filenames_list
    }

# Model Finetuning:

In [ ]:
import csv
import os
from transformers import EarlyStoppingCallback

EPOCHS_LIST = [3]
LEARNING_RATES = [2e-5]
WEIGHT_DECAYS = [0.01]
BATCH_SIZES = [8]
CHUNK_THRESHES = [0.1, 0.2, 0.3, 0.4, 0.5]
LAYERS_TO_UNFREEZE = [0, -1, 4]

early_stopping_callback = EarlyStoppingCallback(
    early_stopping_patience=2,
    early_stopping_threshold=0.0
)

#  Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0
cnt = 0
for dataset in DATASET_ROOTS:
    for cwe_id in ALLOWED_CWE_IDS:
        print(f"\n--- Grid Search for {cwe_id} ---")
        samples = collect_files_for_cwe(cwe_id, dataset)
        random.seed(SEED)
        random.shuffle(samples)
        raw_dataset = Dataset.from_list(samples)
        train_test = raw_dataset.train_test_split(test_size=0.2, seed=SEED)
        train_raw = train_test["train"]
        eval_raw = train_test["test"]
        tokenized_train = train_raw.map(tokenize_example, batched=True, remove_columns=["filename", "code"])
        tokenized_eval = eval_raw.map(tokenize_example, batched=True, remove_columns=["filename", "code"])
        tokenized_train.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label', 'filename'])
        tokenized_eval.set_format(type='torch', columns=['input_ids', 'attention_mask', 'label', 'filename'])

        train_dataset = tokenized_train
        eval_dataset = tokenized_eval
        filenames = eval_dataset["filename"]

        log_path = f"./models/vulberta_{cwe_id}/gridsearch_results.csv"
        os.makedirs(os.path.dirname(log_path), exist_ok=True)
        with open(log_path, "w", newline="") as f:
            writer = csv.writer(f)
            writer.writerow(["epochs", "lr", "weight_decay", "batch_size", "unfrozen_layers", "chunk_thresh", "precision", "recall", "f1", "accuracy", "confusion_matrix"])
            
        best_f1 = -1
        best_dir = None

        for epochs in EPOCHS_LIST:
            for lr in LEARNING_RATES:
                for wd in WEIGHT_DECAYS:
                    for batch_size in BATCH_SIZES:
                        for unfrozen in LAYERS_TO_UNFREEZE:
                            for chunk_thresh in CHUNK_THRESHES:
                                if cnt < 0:
                                    cnt += 1
                                    continue
                                print(f"\nRunning with epochs={epochs}, lr={lr}, wd={wd}, batch_size={batch_size}, ch_thresh={chunk_thresh}, unfrozen_layers={unfrozen}, dataset={dataset}")
                                model = AutoModelForSequenceClassification.from_pretrained(vulBERTa, num_labels=2).to(device)

                                # roberta has 12 layers.
                                if (unfrozen == -1): #make all layers trainable
                                    for param in model.parameters():
                                        param.requires_grad = True
                                
                                else:
                                    if unfrozen >= 6:
                                        if hasattr(model.base_model, "embeddings"):
                                            for param in model.base_model.embeddings.parameters():
                                                param.requires_grad = True

                                    if hasattr(model.base_model, 'encoder'):
                                        encoder_layers = model.base_model.encoder.layer
                                        if isinstance(encoder_layers, torch.nn.ModuleList):
                                            for layer in encoder_layers[-unfrozen:]:
                                                for param in layer.parameters():
                                                    param.requires_grad = True

                                    for param in model.classifier.parameters():
                                        param.requires_grad = True

                                optimizer = AdamW(model.parameters(), lr=lr, weight_decay=wd)
                                num_train_steps = len(train_dataset) * epochs
                                warmup_steps = int(0.1 * num_train_steps)
                                scheduler = get_cosine_schedule_with_warmup(optimizer, warmup_steps, num_train_steps)

                                output_dir = f"./models/vulberta_{cwe_id}/gridsearch/ep{epochs}_lr{lr}_wd{wd}_bs{batch_size}_uf{unfrozen}_ct{chunk_thresh}"
                                training_args = TrainingArguments(
                                    output_dir=output_dir,
                                    evaluation_strategy="epoch",
                                    learning_rate=lr,
                                    per_device_train_batch_size=batch_size,
                                    per_device_eval_batch_size=batch_size,
                                    num_train_epochs=epochs,
                                    weight_decay=wd,
                                    save_strategy="epoch",
                                    load_best_model_at_end=True,
                                    metric_for_best_model="eval_f1",
                                    greater_is_better=True,
                                    remove_unused_columns=False,
                                    logging_dir="./logs",
                                    logging_strategy="epoch",
                                    save_total_limit=1,
                                )

                                trainer = FileAwareTrainer(
                                    model=model,
                                    args=training_args,
                                    train_dataset=train_dataset,
                                    eval_dataset=eval_dataset,
                                    compute_metrics=compute_file_metrics_builder(filenames, chunk_thresh),
                                    optimizers=(optimizer, scheduler),
                                    callbacks=[early_stopping_callback]
                                )

                                trainer.train()
                                trainer.save_model(output_dir + "/final")

                                metrics = trainer.evaluate()
                                precision = metrics["eval_precision"]
                                recall = metrics["eval_recall"]
                                f1 = metrics["eval_f1"]
                                accuracy = metrics["eval_accuracy"]
                                confusion = metrics["eval_confusion_matrix"]

                                with open(log_path, "a", newline="") as f:
                                    writer = csv.writer(f)
                                    writer.writerow([epochs, lr, wd, batch_size, unfrozen, chunk_thresh, precision, recall, f1, accuracy, confusion])

                                if f1 > best_f1:
                                    best_f1 = f1
                                    best_dir = output_dir
                                    best_thresh = chunk_thresh
                                                            
        if best_dir is not None:
            os.system(f"cp -r {best_dir}/final ./models/vulberta_{cwe_id}/best_model")
            print(f"\nBest model for {cwe_id} saved from: {best_dir} with F1={best_f1:.4f}")

--- Grid Search for CWE-89 ---
554

Map:   0%|          | 0/443 [00:00<?, ? examples/s]

Token indices sequence length is longer than the specified maximum sequence length for this model (7581 > 1026). Running this sequence through the model will result in indexing errors

Map:   0%|          | 0/111 [00:00<?, ? examples/s]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[10, 48], [12, 41]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[10, 48], [12, 41]]
chunk level: [[414, 848], [477, 249]]

Trainer is attempting to log a value of "[[0, 58], [3, 50]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [3, 50]]
chunk level: [[93, 1169], [310, 416]]

Trainer is attempting to log a value of "[[30, 28], [46, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[30, 28], [46, 7]]
chunk level: [[469, 793], [679, 47]]

Trainer is attempting to log a value of "[[0, 58], [3, 50]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [3, 50]]
chunk level: [[93, 1169], [310, 416]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [18, 35]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [18, 35]]
chunk level: [[418, 844], [479, 247]]

Trainer is attempting to log a value of "[[1, 57], [0, 53]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [0, 53]]
chunk level: [[31, 1231], [164, 562]]

Trainer is attempting to log a value of "[[21, 37], [42, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[21, 37], [42, 11]]
chunk level: [[390, 872], [659, 67]]

Trainer is attempting to log a value of "[[1, 57], [0, 53]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [0, 53]]
chunk level: [[31, 1231], [164, 562]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[17, 41], [29, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 41], [29, 24]]
chunk level: [[424, 838], [492, 234]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[24, 1238], [174, 552]]

Trainer is attempting to log a value of "[[35, 23], [46, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[35, 23], [46, 7]]
chunk level: [[429, 833], [672, 54]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[24, 1238], [174, 552]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[19, 39], [32, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[19, 39], [32, 21]]
chunk level: [[400, 862], [474, 252]]

Trainer is attempting to log a value of "[[0, 58], [5, 48]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [5, 48]]
chunk level: [[33, 1229], [201, 525]]

Trainer is attempting to log a value of "[[30, 28], [45, 8]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[30, 28], [45, 8]]
chunk level: [[406, 856], [646, 80]]

Trainer is attempting to log a value of "[[0, 58], [5, 48]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [5, 48]]
chunk level: [[33, 1229], [201, 525]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[27, 31], [35, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[27, 31], [35, 18]]
chunk level: [[415, 847], [480, 246]]

Trainer is attempting to log a value of "[[2, 56], [21, 32]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [21, 32]]
chunk level: [[113, 1149], [385, 341]]

Trainer is attempting to log a value of "[[34, 24], [48, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[34, 24], [48, 5]]
chunk level: [[377, 885], [644, 82]]

Trainer is attempting to log a value of "[[2, 56], [21, 32]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [21, 32]]
chunk level: [[113, 1149], [385, 341]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[3, 55], [7, 46]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 55], [7, 46]]
chunk level: [[361, 901], [449, 277]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[11, 1251], [123, 603]]

Trainer is attempting to log a value of "[[27, 31], [41, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[27, 31], [41, 12]]
chunk level: [[440, 822], [661, 65]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[11, 1251], [123, 603]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [18, 35]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [18, 35]]
chunk level: [[407, 855], [477, 249]]

Trainer is attempting to log a value of "[[1, 57], [2, 51]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [2, 51]]
chunk level: [[40, 1222], [222, 504]]

Trainer is attempting to log a value of "[[33, 25], [42, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[33, 25], [42, 11]]
chunk level: [[479, 783], [662, 64]]

Trainer is attempting to log a value of "[[1, 57], [2, 51]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [2, 51]]
chunk level: [[40, 1222], [222, 504]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[17, 41], [29, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 41], [29, 24]]
chunk level: [[404, 858], [487, 239]]

Trainer is attempting to log a value of "[[2, 56], [6, 47]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [6, 47]]
chunk level: [[38, 1224], [183, 543]]

Trainer is attempting to log a value of "[[30, 28], [46, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[30, 28], [46, 7]]
chunk level: [[404, 858], [659, 67]]

Trainer is attempting to log a value of "[[2, 56], [6, 47]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [6, 47]]
chunk level: [[38, 1224], [183, 543]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[20, 38], [29, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[20, 38], [29, 24]]
chunk level: [[391, 871], [449, 277]]

Trainer is attempting to log a value of "[[1, 57], [5, 48]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [5, 48]]
chunk level: [[47, 1215], [207, 519]]

Trainer is attempting to log a value of "[[31, 27], [45, 8]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[31, 27], [45, 8]]
chunk level: [[401, 861], [631, 95]]

Trainer is attempting to log a value of "[[1, 57], [5, 48]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 57], [5, 48]]
chunk level: [[47, 1215], [207, 519]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[26, 32], [34, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[26, 32], [34, 19]]
chunk level: [[407, 855], [470, 256]]

Trainer is attempting to log a value of "[[0, 58], [8, 45]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [8, 45]]
chunk level: [[61, 1201], [255, 471]]

Trainer is attempting to log a value of "[[38, 20], [51, 2]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[38, 20], [51, 2]]
chunk level: [[479, 783], [675, 51]]

Trainer is attempting to log a value of "[[0, 58], [8, 45]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [8, 45]]
chunk level: [[61, 1201], [255, 471]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [11, 42]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [11, 42]]
chunk level: [[398, 864], [473, 253]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[15, 1247], [140, 586]]

Trainer is attempting to log a value of "[[25, 33], [39, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[25, 33], [39, 14]]
chunk level: [[443, 819], [669, 57]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[15, 1247], [140, 586]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [21, 32]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [21, 32]]
chunk level: [[416, 846], [477, 249]]

Trainer is attempting to log a value of "[[0, 58], [0, 53]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [0, 53]]
chunk level: [[19, 1243], [66, 660]]

Trainer is attempting to log a value of "[[39, 19], [49, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[39, 19], [49, 4]]
chunk level: [[521, 741], [694, 32]]

Trainer is attempting to log a value of "[[0, 58], [0, 53]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [0, 53]]
chunk level: [[19, 1243], [66, 660]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[17, 41], [28, 25]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 41], [28, 25]]
chunk level: [[404, 858], [475, 251]]

Trainer is attempting to log a value of "[[0, 58], [3, 50]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [3, 50]]
chunk level: [[45, 1217], [215, 511]]

Trainer is attempting to log a value of "[[29, 29], [46, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[29, 29], [46, 7]]
chunk level: [[419, 843], [653, 73]]

Trainer is attempting to log a value of "[[0, 58], [3, 50]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [3, 50]]
chunk level: [[45, 1217], [215, 511]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[23, 35], [32, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[23, 35], [32, 21]]
chunk level: [[415, 847], [473, 253]]

Trainer is attempting to log a value of "[[2, 56], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [9, 44]]
chunk level: [[73, 1189], [277, 449]]

Trainer is attempting to log a value of "[[36, 22], [49, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[36, 22], [49, 4]]
chunk level: [[453, 809], [669, 57]]

Trainer is attempting to log a value of "[[2, 56], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 56], [9, 44]]
chunk level: [[73, 1189], [277, 449]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[27, 31], [34, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[27, 31], [34, 19]]
chunk level: [[416, 846], [470, 256]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[1, 1261], [8, 718]]

Trainer is attempting to log a value of "[[33, 25], [42, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[33, 25], [42, 11]]
chunk level: [[419, 843], [554, 172]]

Trainer is attempting to log a value of "[[0, 58], [1, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 58], [1, 52]]
chunk level: [[1, 1261], [8, 718]]

Best model for CWE-89 saved from: ./models/vulberta_CWE-89/gridsearch/ep3_lr2e-05_wd0.01_bs8_uf0_ct0.2 with F1=0.6503

--- Grid Search for CWE-79 ---
2024

Map:   0%|          | 0/1619 [00:00<?, ? examples/s]

Map:   0%|          | 0/405 [00:00<?, ? examples/s]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[152, 23], [201, 29]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[152, 23], [201, 29]]
chunk level: [[1934, 275], [2754, 57]]

Trainer is attempting to log a value of "[[169, 6], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [218, 12]]
chunk level: [[2033, 176], [2795, 16]]

Trainer is attempting to log a value of "[[139, 36], [199, 31]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[139, 36], [199, 31]]
chunk level: [[1652, 557], [2734, 77]]

Trainer is attempting to log a value of "[[139, 36], [199, 31]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[139, 36], [199, 31]]
chunk level: [[1652, 557], [2734, 77]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[173, 2], [219, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[173, 2], [219, 11]]
chunk level: [[2113, 96], [2796, 15]]

Trainer is attempting to log a value of "[[162, 13], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[162, 13], [207, 23]]
chunk level: [[1936, 273], [2747, 64]]

Trainer is attempting to log a value of "[[174, 1], [221, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[174, 1], [221, 9]]
chunk level: [[2116, 93], [2802, 9]]

Trainer is attempting to log a value of "[[162, 13], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[162, 13], [207, 23]]
chunk level: [[1936, 273], [2747, 64]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[172, 3], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[172, 3], [218, 12]]
chunk level: [[2052, 157], [2794, 17]]

Trainer is attempting to log a value of "[[168, 7], [217, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[168, 7], [217, 13]]
chunk level: [[1977, 232], [2785, 26]]

Trainer is attempting to log a value of "[[144, 31], [204, 26]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [204, 26]]
chunk level: [[1531, 678], [2657, 154]]

Trainer is attempting to log a value of "[[144, 31], [204, 26]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [204, 26]]
chunk level: [[1531, 678], [2657, 154]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[163, 12], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[163, 12], [218, 12]]
chunk level: [[1960, 249], [2775, 36]]

Trainer is attempting to log a value of "[[170, 5], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[170, 5], [220, 10]]
chunk level: [[1984, 225], [2789, 22]]

Trainer is attempting to log a value of "[[138, 37], [205, 25]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[138, 37], [205, 25]]
chunk level: [[1334, 875], [2576, 235]]

Trainer is attempting to log a value of "[[138, 37], [205, 25]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[138, 37], [205, 25]]
chunk level: [[1334, 875], [2576, 235]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[172, 3], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[172, 3], [220, 10]]
chunk level: [[2051, 158], [2793, 18]]

Trainer is attempting to log a value of "[[172, 3], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[172, 3], [220, 10]]
chunk level: [[1989, 220], [2785, 26]]

Trainer is attempting to log a value of "[[142, 33], [201, 29]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [201, 29]]
chunk level: [[1437, 772], [2599, 212]]

Trainer is attempting to log a value of "[[142, 33], [201, 29]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [201, 29]]
chunk level: [[1437, 772], [2599, 212]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[158, 17], [209, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[158, 17], [209, 21]]
chunk level: [[1968, 241], [2784, 27]]

Trainer is attempting to log a value of "[[161, 14], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[161, 14], [207, 23]]
chunk level: [[1899, 310], [2757, 54]]

Trainer is attempting to log a value of "[[144, 31], [201, 29]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [201, 29]]
chunk level: [[1731, 478], [2768, 43]]

Trainer is attempting to log a value of "[[144, 31], [201, 29]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [201, 29]]
chunk level: [[1731, 478], [2768, 43]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[165, 10], [215, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[165, 10], [215, 15]]
chunk level: [[2015, 194], [2790, 21]]

Trainer is attempting to log a value of "[[172, 3], [221, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[172, 3], [221, 9]]
chunk level: [[2092, 117], [2798, 13]]

Trainer is attempting to log a value of "[[119, 56], [178, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[119, 56], [178, 52]]
chunk level: [[1316, 893], [2492, 319]]

Trainer is attempting to log a value of "[[119, 56], [178, 52]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[119, 56], [178, 52]]
chunk level: [[1316, 893], [2492, 319]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[162, 13], [215, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[162, 13], [215, 15]]
chunk level: [[1945, 264], [2779, 32]]

Trainer is attempting to log a value of "[[171, 4], [217, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[171, 4], [217, 13]]
chunk level: [[1985, 224], [2779, 32]]

Trainer is attempting to log a value of "[[144, 31], [205, 25]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [205, 25]]
chunk level: [[1593, 616], [2720, 91]]

Trainer is attempting to log a value of "[[144, 31], [205, 25]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [205, 25]]
chunk level: [[1593, 616], [2720, 91]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[171, 4], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[171, 4], [220, 10]]
chunk level: [[2023, 186], [2794, 17]]

Trainer is attempting to log a value of "[[169, 6], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [220, 10]]
chunk level: [[1942, 267], [2784, 27]]

Trainer is attempting to log a value of "[[145, 30], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[145, 30], [207, 23]]
chunk level: [[1481, 728], [2689, 122]]

Trainer is attempting to log a value of "[[145, 30], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[145, 30], [207, 23]]
chunk level: [[1481, 728], [2689, 122]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[164, 11], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[164, 11], [218, 12]]
chunk level: [[1973, 236], [2788, 23]]

Trainer is attempting to log a value of "[[169, 6], [221, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [221, 9]]
chunk level: [[1971, 238], [2781, 30]]

Trainer is attempting to log a value of "[[144, 31], [209, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [209, 21]]
chunk level: [[1375, 834], [2625, 186]]

Trainer is attempting to log a value of "[[144, 31], [209, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[144, 31], [209, 21]]
chunk level: [[1375, 834], [2625, 186]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[162, 13], [210, 20]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[162, 13], [210, 20]]
chunk level: [[1997, 212], [2786, 25]]

Trainer is attempting to log a value of "[[164, 11], [211, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[164, 11], [211, 19]]
chunk level: [[1930, 279], [2777, 34]]

Trainer is attempting to log a value of "[[96, 79], [160, 70]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[96, 79], [160, 70]]
chunk level: [[1338, 871], [2614, 197]]

Trainer is attempting to log a value of "[[96, 79], [160, 70]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[96, 79], [160, 70]]
chunk level: [[1338, 871], [2614, 197]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[159, 16], [212, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[159, 16], [212, 18]]
chunk level: [[1974, 235], [2763, 48]]

Trainer is attempting to log a value of "[[167, 8], [217, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[167, 8], [217, 13]]
chunk level: [[1998, 211], [2785, 26]]

Trainer is attempting to log a value of "[[140, 35], [203, 27]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[140, 35], [203, 27]]
chunk level: [[1697, 512], [2732, 79]]

Trainer is attempting to log a value of "[[140, 35], [203, 27]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[140, 35], [203, 27]]
chunk level: [[1697, 512], [2732, 79]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[164, 11], [215, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[164, 11], [215, 15]]
chunk level: [[1952, 257], [2769, 42]]

Trainer is attempting to log a value of "[[166, 9], [216, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[166, 9], [216, 14]]
chunk level: [[1905, 304], [2773, 38]]

Trainer is attempting to log a value of "[[162, 13], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[162, 13], [220, 10]]
chunk level: [[1748, 461], [2768, 43]]

Trainer is attempting to log a value of "[[164, 11], [215, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[164, 11], [215, 15]]
chunk level: [[1952, 257], [2769, 42]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[170, 5], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[170, 5], [218, 12]]
chunk level: [[1999, 210], [2787, 24]]

Trainer is attempting to log a value of "[[167, 8], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[167, 8], [218, 12]]
chunk level: [[1875, 334], [2765, 46]]

Trainer is attempting to log a value of "[[153, 22], [208, 22]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[153, 22], [208, 22]]
chunk level: [[1553, 656], [2632, 179]]

Trainer is attempting to log a value of "[[153, 22], [208, 22]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[153, 22], [208, 22]]
chunk level: [[1553, 656], [2632, 179]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[166, 9], [219, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[166, 9], [219, 11]]
chunk level: [[2001, 208], [2788, 23]]

Trainer is attempting to log a value of "[[166, 9], [221, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[166, 9], [221, 9]]
chunk level: [[1949, 260], [2777, 34]]

Trainer is attempting to log a value of "[[142, 33], [206, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [206, 24]]
chunk level: [[1373, 836], [2544, 267]]

Trainer is attempting to log a value of "[[142, 33], [206, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [206, 24]]
chunk level: [[1373, 836], [2544, 267]]

Best model for CWE-79 saved from: ./models/vulberta_CWE-79/gridsearch/ep3_lr2e-05_wd0.01_bs8_uf4_ct0.1 with F1=0.3694

--- Grid Search for CWE-787 ---
270

Map:   0%|          | 0/216 [00:00<?, ? examples/s]

Map:   0%|          | 0/54 [00:00<?, ? examples/s]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 21], [14, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 21], [14, 12]]
chunk level: [[580, 485], [1302, 149]]

Trainer is attempting to log a value of "[[1, 27], [8, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [8, 18]]
chunk level: [[241, 824], [1083, 368]]

Trainer is attempting to log a value of "[[13, 15], [21, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[13, 15], [21, 5]]
chunk level: [[678, 387], [1396, 55]]

Trainer is attempting to log a value of "[[1, 27], [8, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [8, 18]]
chunk level: [[241, 824], [1083, 368]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 17], [16, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 17], [16, 10]]
chunk level: [[567, 498], [1293, 158]]

Trainer is attempting to log a value of "[[1, 27], [7, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [7, 19]]
chunk level: [[194, 871], [1000, 451]]

Trainer is attempting to log a value of "[[18, 10], [23, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[18, 10], [23, 3]]
chunk level: [[656, 409], [1391, 60]]

Trainer is attempting to log a value of "[[1, 27], [7, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [7, 19]]
chunk level: [[194, 871], [1000, 451]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[13, 15], [19, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[13, 15], [19, 7]]
chunk level: [[576, 489], [1301, 150]]

Trainer is attempting to log a value of "[[3, 25], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 25], [13, 13]]
chunk level: [[228, 837], [1066, 385]]

Trainer is attempting to log a value of "[[16, 12], [23, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[16, 12], [23, 3]]
chunk level: [[696, 369], [1269, 182]]

Trainer is attempting to log a value of "[[3, 25], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 25], [13, 13]]
chunk level: [[228, 837], [1066, 385]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[14, 14], [19, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[14, 14], [19, 7]]
chunk level: [[559, 506], [1293, 158]]

Trainer is attempting to log a value of "[[4, 24], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [12, 14]]
chunk level: [[200, 865], [1059, 392]]

Trainer is attempting to log a value of "[[16, 12], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[16, 12], [25, 1]]
chunk level: [[623, 442], [1394, 57]]

Trainer is attempting to log a value of "[[4, 24], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [12, 14]]
chunk level: [[200, 865], [1059, 392]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=0, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[17, 11], [22, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 11], [22, 4]]
chunk level: [[592, 473], [1308, 143]]

Trainer is attempting to log a value of "[[4, 24], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [12, 14]]
chunk level: [[159, 906], [967, 484]]

Trainer is attempting to log a value of "[[23, 5], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[23, 5], [25, 1]]
chunk level: [[757, 308], [1384, 67]]

Trainer is attempting to log a value of "[[4, 24], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [12, 14]]
chunk level: [[159, 906], [967, 484]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[6, 22], [15, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[6, 22], [15, 11]]
chunk level: [[591, 474], [1306, 145]]

Trainer is attempting to log a value of "[[0, 28], [6, 20]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 28], [6, 20]]
chunk level: [[156, 909], [940, 511]]

Trainer is attempting to log a value of "[[11, 17], [19, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 17], [19, 7]]
chunk level: [[657, 408], [1322, 129]]

Trainer is attempting to log a value of "[[0, 28], [6, 20]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[0, 28], [6, 20]]
chunk level: [[156, 909], [940, 511]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[13, 15], [17, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[13, 15], [17, 9]]
chunk level: [[620, 445], [1321, 130]]

Trainer is attempting to log a value of "[[1, 27], [8, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [8, 18]]
chunk level: [[132, 933], [961, 490]]

Trainer is attempting to log a value of "[[16, 12], [21, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[16, 12], [21, 5]]
chunk level: [[758, 307], [1341, 110]]

Trainer is attempting to log a value of "[[1, 27], [8, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [8, 18]]
chunk level: [[132, 933], [961, 490]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[12, 16], [19, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[12, 16], [19, 7]]
chunk level: [[563, 502], [1291, 160]]

Trainer is attempting to log a value of "[[5, 23], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [12, 14]]
chunk level: [[229, 836], [1078, 373]]

Trainer is attempting to log a value of "[[17, 11], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 11], [25, 1]]
chunk level: [[664, 401], [1430, 21]]

Trainer is attempting to log a value of "[[5, 23], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [12, 14]]
chunk level: [[229, 836], [1078, 373]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[13, 15], [20, 6]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[13, 15], [20, 6]]
chunk level: [[588, 477], [1307, 144]]

Trainer is attempting to log a value of "[[5, 23], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [13, 13]]
chunk level: [[220, 845], [1083, 368]]

Trainer is attempting to log a value of "[[17, 11], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[17, 11], [25, 1]]
chunk level: [[646, 419], [1320, 131]]

Trainer is attempting to log a value of "[[5, 23], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [13, 13]]
chunk level: [[220, 845], [1083, 368]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=-1, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[19, 9], [22, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[19, 9], [22, 4]]
chunk level: [[708, 357], [1339, 112]]

Trainer is attempting to log a value of "[[5, 23], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [13, 13]]
chunk level: [[228, 837], [1085, 366]]

Trainer is attempting to log a value of "[[16, 12], [23, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[16, 12], [23, 3]]
chunk level: [[640, 425], [1273, 178]]

Trainer is attempting to log a value of "[[5, 23], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [13, 13]]
chunk level: [[228, 837], [1085, 366]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[6, 22], [13, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[6, 22], [13, 13]]
chunk level: [[556, 509], [1283, 168]]

Trainer is attempting to log a value of "[[1, 27], [7, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [7, 19]]
chunk level: [[186, 879], [1002, 449]]

Trainer is attempting to log a value of "[[13, 15], [22, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[13, 15], [22, 4]]
chunk level: [[661, 404], [1387, 64]]

Trainer is attempting to log a value of "[[1, 27], [7, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[1, 27], [7, 19]]
chunk level: [[186, 879], [1002, 449]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[12, 16], [17, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[12, 16], [17, 9]]
chunk level: [[554, 511], [1291, 160]]

Trainer is attempting to log a value of "[[3, 25], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 25], [11, 15]]
chunk level: [[214, 851], [1094, 357]]

Trainer is attempting to log a value of "[[18, 10], [23, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[18, 10], [23, 3]]
chunk level: [[736, 329], [1440, 11]]

Trainer is attempting to log a value of "[[3, 25], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 25], [11, 15]]
chunk level: [[214, 851], [1094, 357]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 17], [19, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 17], [19, 7]]
chunk level: [[563, 502], [1290, 161]]

Trainer is attempting to log a value of "[[2, 26], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 26], [11, 15]]
chunk level: [[196, 869], [1066, 385]]

Trainer is attempting to log a value of "[[18, 10], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[18, 10], [25, 1]]
chunk level: [[735, 330], [1367, 84]]

Trainer is attempting to log a value of "[[2, 26], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[2, 26], [11, 15]]
chunk level: [[196, 869], [1066, 385]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[14, 14], [18, 8]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[14, 14], [18, 8]]
chunk level: [[573, 492], [1288, 163]]

Trainer is attempting to log a value of "[[4, 24], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [11, 15]]
chunk level: [[208, 857], [1068, 383]]

Trainer is attempting to log a value of "[[21, 7], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[21, 7], [25, 1]]
chunk level: [[755, 310], [1417, 34]]

Trainer is attempting to log a value of "[[4, 24], [11, 15]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 24], [11, 15]]
chunk level: [[208, 857], [1068, 383]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=4, dataset=../../CrossVul

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[16, 12], [21, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[16, 12], [21, 5]]
chunk level: [[574, 491], [1310, 141]]

Trainer is attempting to log a value of "[[5, 23], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [12, 14]]
chunk level: [[219, 846], [1050, 401]]

Trainer is attempting to log a value of "[[20, 8], [25, 1]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[20, 8], [25, 1]]
chunk level: [[705, 360], [1364, 87]]

Trainer is attempting to log a value of "[[5, 23], [12, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 23], [12, 14]]
chunk level: [[219, 846], [1050, 401]]

Best model for CWE-787 saved from: ./models/vulberta_CWE-787/gridsearch/ep3_lr2e-05_wd0.01_bs8_uf-1_ct0.1 with F1=0.5405

--- Grid Search for CWE-89 ---
554

Map:   0%|          | 0/443 [00:00<?, ? examples/s]

Map:   0%|          | 0/111 [00:00<?, ? examples/s]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [9, 44]]
chunk level: [[121, 852], [189, 302]]

Trainer is attempting to log a value of "[[3, 55], [8, 45]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 55], [8, 45]]
chunk level: [[51, 922], [167, 324]]

Trainer is attempting to log a value of "[[34, 24], [49, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[34, 24], [49, 4]]
chunk level: [[364, 609], [467, 24]]

Trainer is attempting to log a value of "[[7, 51], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [9, 44]]
chunk level: [[121, 852], [189, 302]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [11, 42]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [11, 42]]
chunk level: [[118, 855], [185, 306]]

Trainer is attempting to log a value of "[[3, 55], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 55], [9, 44]]
chunk level: [[59, 914], [177, 314]]

Trainer is attempting to log a value of "[[33, 25], [48, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[33, 25], [48, 5]]
chunk level: [[333, 640], [466, 25]]

Trainer is attempting to log a value of "[[3, 55], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 55], [9, 44]]
chunk level: [[59, 914], [177, 314]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[121, 852], [189, 302]]

Trainer is attempting to log a value of "[[5, 53], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 53], [15, 38]]
chunk level: [[76, 897], [232, 259]]

Trainer is attempting to log a value of "[[30, 28], [46, 7]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[30, 28], [46, 7]]
chunk level: [[303, 670], [450, 41]]

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[121, 852], [189, 302]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[9, 49], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [15, 38]]
chunk level: [[120, 853], [186, 305]]

Trainer is attempting to log a value of "[[8, 50], [20, 33]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[8, 50], [20, 33]]
chunk level: [[92, 881], [263, 228]]

Trainer is attempting to log a value of "[[36, 22], [48, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[36, 22], [48, 5]]
chunk level: [[341, 632], [463, 28]]

Trainer is attempting to log a value of "[[9, 49], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [15, 38]]
chunk level: [[120, 853], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[120, 853], [186, 305]]

Trainer is attempting to log a value of "[[8, 50], [23, 30]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[8, 50], [23, 30]]
chunk level: [[93, 880], [270, 221]]

Trainer is attempting to log a value of "[[41, 17], [51, 2]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[41, 17], [51, 2]]
chunk level: [[377, 596], [478, 13]]

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[120, 853], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [9, 44]]
chunk level: [[121, 852], [186, 305]]

Trainer is attempting to log a value of "[[5, 53], [11, 42]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 53], [11, 42]]
chunk level: [[87, 886], [270, 221]]

Trainer is attempting to log a value of "[[18, 40], [37, 16]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[18, 40], [37, 16]]
chunk level: [[299, 674], [433, 58]]

Trainer is attempting to log a value of "[[7, 51], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [9, 44]]
chunk level: [[121, 852], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [12, 41]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [12, 41]]
chunk level: [[121, 852], [190, 301]]

Trainer is attempting to log a value of "[[7, 51], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [15, 38]]
chunk level: [[102, 871], [274, 217]]

Trainer is attempting to log a value of "[[29, 29], [45, 8]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[29, 29], [45, 8]]
chunk level: [[312, 661], [454, 37]]

Trainer is attempting to log a value of "[[7, 51], [12, 41]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [12, 41]]
chunk level: [[121, 852], [190, 301]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[120, 853], [186, 305]]

Trainer is attempting to log a value of "[[8, 50], [17, 36]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[8, 50], [17, 36]]
chunk level: [[104, 869], [285, 206]]

Trainer is attempting to log a value of "[[34, 24], [50, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[34, 24], [50, 3]]
chunk level: [[332, 641], [476, 15]]

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[120, 853], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[9, 49], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [16, 37]]
chunk level: [[121, 852], [190, 301]]

Trainer is attempting to log a value of "[[4, 54], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 54], [9, 44]]
chunk level: [[50, 923], [150, 341]]

Trainer is attempting to log a value of "[[39, 19], [51, 2]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[39, 19], [51, 2]]
chunk level: [[386, 587], [477, 14]]

Trainer is attempting to log a value of "[[4, 54], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[4, 54], [9, 44]]
chunk level: [[50, 923], [150, 341]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[121, 852], [189, 302]]

Trainer is attempting to log a value of "[[3, 55], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[3, 55], [15, 38]]
chunk level: [[60, 913], [194, 297]]

Trainer is attempting to log a value of "[[40, 18], [51, 2]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[40, 18], [51, 2]]
chunk level: [[346, 627], [475, 16]]

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[121, 852], [189, 302]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=4, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [9, 44]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [9, 44]]
chunk level: [[121, 852], [189, 302]]

Trainer is attempting to log a value of "[[8, 50], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[8, 50], [15, 38]]
chunk level: [[123, 850], [316, 175]]

Trainer is attempting to log a value of "[[15, 43], [12, 41]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[15, 43], [12, 41]]
chunk level: [[444, 529], [265, 226]]

Trainer is attempting to log a value of "[[15, 43], [12, 41]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[15, 43], [12, 41]]
chunk level: [[444, 529], [265, 226]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=4, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[7, 51], [11, 42]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [11, 42]]
chunk level: [[120, 853], [186, 305]]

Trainer is attempting to log a value of "[[5, 53], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[5, 53], [13, 40]]
chunk level: [[76, 897], [243, 248]]

Trainer is attempting to log a value of "[[32, 26], [49, 4]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[32, 26], [49, 4]]
chunk level: [[312, 661], [462, 29]]

Trainer is attempting to log a value of "[[7, 51], [11, 42]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [11, 42]]
chunk level: [[120, 853], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=4, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[120, 853], [186, 305]]

Trainer is attempting to log a value of "[[7, 51], [19, 34]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[7, 51], [19, 34]]
chunk level: [[104, 869], [289, 202]]

Trainer is attempting to log a value of "[[29, 29], [45, 8]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[29, 29], [45, 8]]
chunk level: [[285, 688], [439, 52]]

Trainer is attempting to log a value of "[[9, 49], [13, 40]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [13, 40]]
chunk level: [[120, 853], [186, 305]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=4, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[10, 48], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[10, 48], [15, 38]]
chunk level: [[122, 851], [189, 302]]

Trainer is attempting to log a value of "[[9, 49], [21, 32]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[9, 49], [21, 32]]
chunk level: [[102, 871], [276, 215]]

Trainer is attempting to log a value of "[[35, 23], [48, 5]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[35, 23], [48, 5]]
chunk level: [[342, 631], [462, 29]]

Trainer is attempting to log a value of "[[10, 48], [15, 38]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[10, 48], [15, 38]]
chunk level: [[122, 851], [189, 302]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=4, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[119, 854], [189, 302]]

Trainer is attempting to log a value of "[[6, 52], [19, 34]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[6, 52], [19, 34]]
chunk level: [[80, 893], [233, 258]]

Trainer is attempting to log a value of "[[39, 19], [50, 3]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[39, 19], [50, 3]]
chunk level: [[376, 597], [479, 12]]

Trainer is attempting to log a value of "[[11, 47], [16, 37]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[11, 47], [16, 37]]
chunk level: [[119, 854], [189, 302]]

Best model for CWE-89 saved from: ./models/vulberta_CWE-89/gridsearch/ep3_lr2e-05_wd0.01_bs8_uf4_ct0.1 with F1=0.5985

--- Grid Search for CWE-79 ---
2024

Map:   0%|          | 0/1619 [00:00<?, ? examples/s]

Map:   0%|          | 0/405 [00:00<?, ? examples/s]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[168, 7], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[168, 7], [218, 12]]
chunk level: [[1517, 111], [2150, 12]]

Trainer is attempting to log a value of "[[148, 27], [206, 24]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[148, 27], [206, 24]]
chunk level: [[1305, 323], [2077, 85]]

Trainer is attempting to log a value of "[[125, 50], [179, 51]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[125, 50], [179, 51]]
chunk level: [[1212, 416], [2014, 148]]

Trainer is attempting to log a value of "[[125, 50], [179, 51]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[125, 50], [179, 51]]
chunk level: [[1212, 416], [2014, 148]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[169, 6], [217, 13]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [217, 13]]
chunk level: [[1514, 114], [2147, 15]]

Trainer is attempting to log a value of "[[142, 33], [194, 36]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [194, 36]]
chunk level: [[1112, 516], [2004, 158]]

Trainer is attempting to log a value of "[[155, 20], [211, 19]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[155, 20], [211, 19]]
chunk level: [[1215, 413], [2032, 130]]

Trainer is attempting to log a value of "[[142, 33], [194, 36]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[142, 33], [194, 36]]
chunk level: [[1112, 516], [2004, 158]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[169, 6], [219, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [219, 11]]
chunk level: [[1517, 111], [2148, 14]]

Trainer is attempting to log a value of "[[141, 34], [194, 36]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [194, 36]]
chunk level: [[1202, 426], [2051, 111]]

Trainer is attempting to log a value of "[[164, 11], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[164, 11], [218, 12]]
chunk level: [[1339, 289], [2139, 23]]

Trainer is attempting to log a value of "[[141, 34], [194, 36]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [194, 36]]
chunk level: [[1202, 426], [2051, 111]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.4, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[171, 4], [219, 11]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[171, 4], [219, 11]]
chunk level: [[1513, 115], [2147, 15]]

Trainer is attempting to log a value of "[[149, 26], [209, 21]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[149, 26], [209, 21]]
chunk level: [[1291, 337], [2006, 156]]

Trainer is attempting to log a value of "[[154, 21], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[154, 21], [207, 23]]
chunk level: [[1306, 322], [2115, 47]]

Trainer is attempting to log a value of "[[154, 21], [207, 23]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[154, 21], [207, 23]]
chunk level: [[1306, 322], [2115, 47]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.5, unfrozen_layers=0, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[171, 4], [220, 10]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[171, 4], [220, 10]]
chunk level: [[1518, 110], [2148, 14]]

Trainer is attempting to log a value of "[[108, 67], [166, 64]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[108, 67], [166, 64]]
chunk level: [[829, 799], [1781, 381]]

Trainer is attempting to log a value of "[[156, 19], [212, 18]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[156, 19], [212, 18]]
chunk level: [[1279, 349], [2119, 43]]

Trainer is attempting to log a value of "[[108, 67], [166, 64]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[108, 67], [166, 64]]
chunk level: [[829, 799], [1781, 381]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.1, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[168, 7], [216, 14]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[168, 7], [216, 14]]
chunk level: [[1514, 114], [2148, 14]]

Trainer is attempting to log a value of "[[126, 49], [191, 39]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[126, 49], [191, 39]]
chunk level: [[1210, 418], [2058, 104]]

Trainer is attempting to log a value of "[[141, 34], [198, 32]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [198, 32]]
chunk level: [[1279, 349], [2090, 72]]

Trainer is attempting to log a value of "[[126, 49], [191, 39]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[126, 49], [191, 39]]
chunk level: [[1210, 418], [2058, 104]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.2, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[169, 6], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [218, 12]]
chunk level: [[1518, 110], [2149, 13]]

Trainer is attempting to log a value of "[[141, 34], [197, 33]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [197, 33]]
chunk level: [[1258, 370], [2087, 75]]

Trainer is attempting to log a value of "[[169, 6], [221, 9]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [221, 9]]
chunk level: [[1435, 193], [2153, 9]]

Trainer is attempting to log a value of "[[141, 34], [197, 33]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [197, 33]]
chunk level: [[1258, 370], [2087, 75]]

Running with epochs=3, lr=2e-05, wd=0.01, batch_size=8, ch_thresh=0.3, unfrozen_layers=-1, dataset=../../Preprocessed/Rename

C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\optimization.py:591: FutureWarning: This implementation of AdamW is deprecated and will be removed in a future version. Use the PyTorch implementation torch.optim.AdamW instead, or set `no_deprecation_warning=True` to disable this warning
  warnings.warn(
C:\Users\robpi\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\transformers\training_args.py:1575: FutureWarning: `evaluation_strategy` is deprecated and will be removed in version 4.46 of 🤗 Transformers. Use `eval_strategy` instead
  warnings.warn(

Trainer is attempting to log a value of "[[169, 6], [218, 12]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[169, 6], [218, 12]]
chunk level: [[1516, 112], [2147, 15]]

Trainer is attempting to log a value of "[[141, 34], [197, 33]]" of type <class 'list'> for key "eval/confusion_matrix" as a scalar. This invocation of Tensorboard's writer.add_scalar() is incorrect so we dropped this attribute.

file level: [[141, 34], [197, 33]]
chunk level: [[1252, 376], [2059, 103]]